services:
    advertisement:
        build: ./advertisement
        volumes:
            - ./volume:/volume
        ports:
            - 3000:3000
        environment:
            - PORT=3000
            - DBURL=mongodb://root:example@mongo:27017/library?authSource=admin
            - SESSION_SECRET=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

    mongo:
        image: mongo
        restart: always
        volumes:
            - ./volume/mongo:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH: false
